apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-whatsapp
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    example:
      endpoint: /example
      method: POST
      port: '12000'
      url: ''
